name: Deploy to Heroku Hosting on PR
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
jobs:
  build_backend:
    runs-on: ubuntu-latest  
    steps:
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.12.12 # This is the action
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "academic-sofkau"
          heroku_email: "alzategomez.raul@gmail.com"
          justlogin: true
      - run: chmod +x mvnw && ./mvnw clean compile 
      - run: ./mvnw clean  heroku:deploy

